"""End-to-end conversion test for BEVFusion's real mmdet3d SparseEncoder
(the LiDAR backbone), using the TLSparseConv3D custom op (see
onnx2kerastl/customonnxlayer/onnxsparseconv.py).

The fixture file (encoder_extract.npz) is generated by instantiating a real
SparseEncoder (real architecture: 12 SparseConvolution layers -- conv_input,
4 encoder stages, conv_out -- each real kernel_size/stride/padding/dilation,
including the asymmetric-padding stage and conv_out's non-cubic kernel) with
real compiled spconv ops on a CUDA box (mmdet3d requires a compiled CUDA
extension; not runnable in this repo's plain CPU env), running its real
forward pass on random input, and dumping every layer's weight/BN params plus
the input/output. No trained checkpoint was available, so weights are
randomly initialized -- this test validates the CONVERTER and graph
construction (real architecture, real per-layer configs, real BN fusion,
real dense/reshape tail) are correct, which is independent of whether the
weights are trained.

Regenerate via bevfusion's mmdet3d + a real spconv build:
    docker exec <container> python <ec2_extract_encoder.py-equivalent>
(see StackAV BEVFusion integration notes / scratchpad/sparse_conv_poc on the
authoring machine for the exact extraction script used).
"""
import os

import numpy as np
import onnx
import pytest
import tensorflow as tf
from onnx import TensorProto, helper

from onnx2kerastl import onnx_to_keras

FIXTURE_PATH = os.path.expanduser("~/tensorleap/data/bevfusion-sparse-encoder/encoder_extract.npz")


def _build_onnx_model(d):
    num_layers = int(d["num_layers"])
    sparse_shape = [int(x) for x in d["sparse_shape"]]
    in_coords, in_feats = d["in_coords"], d["in_feats"]
    n_in, c_in = in_coords.shape[0], in_feats.shape[1]

    nodes, initializers = [], []
    coords_name, feats_name = "coords_0", "feats_0"
    cur_shape = sparse_shape

    for i in range(num_layers):
        kernel_size = [int(x) for x in d[f"layer{i}_kernel_size"]]
        stride = [int(x) for x in d[f"layer{i}_stride"]]
        padding = [int(x) for x in d[f"layer{i}_padding"]]
        dilation = [1, 1, 1]
        subm = int(d[f"layer{i}_subm"])
        weight, bias = d[f"layer{i}_weight"], d[f"layer{i}_bias"]

        w_name, b_name = f"weight{i}", f"bias{i}"
        initializers.append(helper.make_tensor(w_name, TensorProto.FLOAT, weight.shape, weight.flatten()))
        initializers.append(helper.make_tensor(b_name, TensorProto.FLOAT, bias.shape, bias.flatten()))

        next_coords, conv_feats = f"coords_conv_{i}", f"feats_conv_{i}"
        nodes.append(helper.make_node(
            "TLSparseConv3D", [coords_name, feats_name, w_name, b_name], [next_coords, conv_feats],
            name=f"conv{i}", domain="ai.tensorleap",
            kernel_size=kernel_size, stride=stride, padding=padding, dilation=dilation,
            in_shape=cur_shape, subm=subm,
        ))

        gamma, beta = d[f"layer{i}_bn_gamma"], d[f"layer{i}_bn_beta"]
        mean, var, eps = d[f"layer{i}_bn_mean"], d[f"layer{i}_bn_var"], float(d[f"layer{i}_bn_eps"])
        scale = (gamma / np.sqrt(var + eps)).astype(np.float32)
        shift = (beta - mean * scale).astype(np.float32)
        scale_name, shift_name = f"bn_scale{i}", f"bn_shift{i}"
        initializers.append(helper.make_tensor(scale_name, TensorProto.FLOAT, scale.shape, scale))
        initializers.append(helper.make_tensor(shift_name, TensorProto.FLOAT, shift.shape, shift))

        bn_mul, bn_add, relu_out = f"bn_mul_{i}", f"bn_add_{i}", f"feats_{i + 1}"
        nodes.append(helper.make_node("Mul", [conv_feats, scale_name], [bn_mul], name=f"bn_mul{i}"))
        nodes.append(helper.make_node("Add", [bn_mul, shift_name], [bn_add], name=f"bn_add{i}"))
        nodes.append(helper.make_node("Relu", [bn_add], [relu_out], name=f"relu{i}"))

        out_shape = cur_shape if subm else [
            (cur_shape[ax] + 2 * padding[ax] - dilation[ax] * (kernel_size[ax] - 1) - 1) // stride[ax] + 1
            for ax in range(3)
        ]
        coords_name, feats_name, cur_shape = next_coords, relu_out, out_shape

    c_final = int(d[f"layer{num_layers - 1}_weight"].shape[-1])
    final_spatial_shape = cur_shape

    initializers += [
        helper.make_tensor("slice_starts", TensorProto.INT64, [1], [0]),
        helper.make_tensor("slice_ends", TensorProto.INT64, [1], [1]),
        helper.make_tensor("slice_axes", TensorProto.INT64, [1], [1]),
        helper.make_tensor("zero_scalar", TensorProto.INT64, [1], [0]),
    ]
    nodes.append(helper.make_node(
        "Slice", [coords_name, "slice_starts", "slice_ends", "slice_axes"], ["coords_col0_tmp"], name="slice_col0"
    ))
    nodes.append(helper.make_node("Mul", ["coords_col0_tmp", "zero_scalar"], ["zero_batch_col"], name="zero_col"))
    nodes.append(helper.make_node("Concat", ["zero_batch_col", coords_name], ["full_indices"], axis=1, name="concat_batch_col"))

    dense_target_shape = [1] + final_spatial_shape + [c_final]
    initializers.append(helper.make_tensor(
        "dense_zero_data", TensorProto.FLOAT, dense_target_shape,
        np.zeros(dense_target_shape, dtype=np.float32).flatten(),
    ))
    nodes.append(helper.make_node("ScatterND", ["dense_zero_data", "full_indices", feats_name], ["dense_scattered"], name="scatter_dense"))
    nodes.append(helper.make_node("Transpose", ["dense_scattered"], ["dense_transposed"], perm=[0, 4, 3, 1, 2], name="dense_transpose"))

    final_shape = [1, c_final * final_spatial_shape[2], final_spatial_shape[0], final_spatial_shape[1]]
    initializers.append(helper.make_tensor("final_reshape_shape", TensorProto.INT64, [4], final_shape))
    nodes.append(helper.make_node("Reshape", ["dense_transposed", "final_reshape_shape"], ["final_output"], name="final_reshape"))

    graph = helper.make_graph(
        nodes, "sparse_encoder_full",
        [
            helper.make_tensor_value_info("coords_0", TensorProto.INT64, [n_in, 3]),
            helper.make_tensor_value_info("feats_0", TensorProto.FLOAT, [n_in, c_in]),
        ],
        [helper.make_tensor_value_info("final_output", TensorProto.FLOAT, final_shape)],
        initializer=initializers,
    )
    model = helper.make_model(
        graph, producer_name="tl_sparse_encoder_test",
        opset_imports=[helper.make_opsetid("", 13), helper.make_opsetid("ai.tensorleap", 1)],
    )
    onnx.checker.check_model(model)
    return model


def _run(fixture_path):
    d = np.load(fixture_path)
    onnx_model = _build_onnx_model(d)

    result = onnx_to_keras(onnx_model, ["coords_0", "feats_0"], name_policy="attach_weights_name", allow_partial_compilation=False)
    keras_model = result.converted_model

    keras_out = keras_model([tf.constant(d["in_coords"]), tf.constant(d["in_feats"])]).numpy()
    expected = d["final_output"]

    assert keras_out.shape == expected.shape, f"shape mismatch: {keras_out.shape} vs {expected.shape}"
    diff = np.abs(expected.astype(np.float64) - keras_out.astype(np.float64))
    mean_error, max_error = float(diff.mean()), float(diff.max())
    print(f"mean_error={mean_error:.8f} max_error={max_error:.8f}")
    assert max_error < 1e-2, f"FAILED: max_error={max_error}"


@pytest.mark.skipif(not os.path.isfile(FIXTURE_PATH), reason=f"fixture not available locally: {FIXTURE_PATH}")
def test_sparse_encoder_full_conversion():
    _run(FIXTURE_PATH)


if __name__ == "__main__":
    _run(FIXTURE_PATH)
    print("PASSED")
