name: Push to Repo B
on: [push]
on:
jobs:
  update-leap-model-parser:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        id: extract_branch
        run: echo "::set-output name=branch_name::$(echo ${GITHUB_REF#refs/heads/})"

      - name: Checkout Repo A
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Create and push branch in Repo B
        run: |
          # Clone Repo B
          git clone https://github.com/yourusername/repo-b.git
          cd repo-b

          # Extract current branch name
          CURRENT_BRANCH=$(echo ${{ steps.extract_branch.outputs.branch_name }})

          # Create a new branch based on the current branch name from Repo A
          NEW_BRANCH="${CURRENT_BRANCH}-from-prev"
          git checkout -b $NEW_BRANCH

          # Push the branch to Repo B
          git push origin $NEW_BRANCH
