name: Push to Repo B
on: [push]
permissions:
    id-token: write # This is required for requesting the JWT
    contents: read  # This is required for actions/checkout
    issues: write   # permits an action to add a comment to an issue.
    pull-requests: write
jobs:
  update-leap-model-parser:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        id: extract_branch
        run: echo "::set-output name=branch_name::$(echo ${GITHUB_REF#refs/heads/})"

      - name: Checkout Repo A
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.TENSORLEAP_OPS_GITHUB_TOKEN }}

#      - name: Set up Git
#        run: |
#          git config --global user.email github-actions@github.com
#          git config --global user.name github-actions

      - name: Create and push branch in Repo B
        env:
          GH_TOKEN: ${{ secrets.TENSORLEAP_OPS_GITHUB_TOKEN }}
        run: |
          # Clone Repo B
          git config user.email github-actions@github.com
          git config user.name github-actions
          git clone https://github.com/tensorleap/leap-model-parser.git
          cd leap-model-parser

          # Extract current branch name
          #CURRENT_BRANCH=$(echo ${{ steps.extract_branch.outputs.branch_name }})

          # Create a new branch based on the current branch name from Repo A
          #NEW_BRANCH="${CURRENT_BRANCH}-from-prev"
          #git checkout -b $NEW_BRANCH

          # Push the branch to Repo B
          #git push origin $NEW_BRANCH
