name: Push to Repo B
on: [push]
permissions:
    id-token: write # This is required for requesting the JWT
    contents: read  # This is required for actions/checkout
    issues: write   # permits an action to add a comment to an issue.
    pull-requests: write
jobs:
  update-leap-model-parser:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        id: extract_branch
        run: echo "::set-output name=branch_name::$(echo ${GITHUB_REF#refs/heads/})"

      - name: Checkout Repo A
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.TENSORLEAP_OPS_GITHUB_TOKEN }}

      - name: Set up Git
        run: |
          git config user.email github-actions@github.com
          git config user.name github-actions

      - name: Clone leap-model-parser using GitHub Script
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.TENSORLEAP_OPS_GITHUB_TOKEN }}
          script: |
            const { exec: githubExec } = require('@actions/github-script@v6');

            async function run() {
              const repoBUrl = "https://github.com/tensorleap/leap-model-parser.git";
              
              // Use GitHub Actions exec to clone repo B
              await githubExec(`git clone ${repoBUrl} repo-b`);
              
              // Change directory to repo-b
              process.chdir('repo-b');
              
              // List files in repo-b after cloning
              await githubExec('ls -l');
            }

            run().catch(err => {
              console.error(err);
              process.exit(1);
            });
