name: Push to O2K
on: [push]
permissions:
    id-token: write # This is required for requesting the JWT
    contents: read  # This is required for actions/checkout
    issues: write   # permits an action to add a comment to an issue.
    pull-requests: write
jobs:
  update-leap-model-parser:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        id: extract_branch
        run: echo "::set-output name=branch_name::$(echo ${GITHUB_REF#refs/heads/})"
      - name: Get package version from pyproject.toml
        run: |
          PACKAGE_VERSION=$(awk -F' = ' '$1 == "version" {gsub(/"/, "", $2); print $2}' pyproject.toml | head -n 1)
          echo "::set-output name=project_version::$VERSION"
      - name: checkout leap model parser
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.TENSORLEAP_OPS_GITHUB_TOKEN }}
          repository: tensorleap/leap-model-parser
      - name: Checkout leap-model-parser
        run: |
          BRANCH="${{ steps.extract_branch.outputs.branch_name }}-from-o2k"
          git config user.email github-actions@github.com
          git config user.name github-actions
          if git fetch origin && git ls-remote --exit-code --heads origin "$BRANCH"; then
              git checkout "$BRANCH"
              git pull origin "$BRANCH"
          else
              git checkout -b "$BRANCH"
          fi
          git push origin "$BRANCH"
          ls -l  # Example command: List files in the checked-out repositor
          echo "1"
